feat: test report

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,10 +28,15 @@ jobs:
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker:latest
+      env:
+        CRITERION_JOBS: N
+        CRITERION_VERBOSITY_LEVEL: 0
+        CRITERION_OUTPUTS: xml:tests_result.xml
+
     steps:
       - name: Installing coverage tools
         run: dnf -y install lcov
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Clean repository
         run: make fclean
       - name: Run tests
@@ -41,8 +46,17 @@ jobs:
           lcov --capture --directory sources/ --output-file tests_coverage.info
           genhtml tests_coverage.info --output-directory CODE_COVERAGE
       - name: Upload tests coverage
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
+        with:
+          name: tests_coverage
+          path: CODE_COVERAGE/*
+      - name: Upload tests results
+        uses: actions/upload-artifact@v3
         with:
           name: tests_results
-          path: |
-            CODE_COVERAGE/*
+          path: tests_results.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: tests_results.xml
